services:
  jaeger:
    image: jaegertracing/all-in-one:1.49
    container_name: jaeger
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411

  signoz:
    image: signoz/signoz:latest
    container_name: signoz
    ports:
      - "3301:3301"   # UI
      - "4319:4318"   # OTLP HTTP
      - "55680:55680" # OTLP gRPC
    environment:
      - TZ=Asia/Ho_Chi_Minh

  backend:
    build: .
    container_name: backend
    ports:
      - "3000:3000"
    depends_on:
      - jaeger
      - signoz
